# Generated by Django 3.2.10 on 2022-01-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="start_location_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="owner",
            field=models.ForeignKey(
                help_text="Player that created the location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="buybackprogram.owner",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="structure_id",
            field=models.BigIntegerField(
                blank=True,
                default=None,
                help_text="The ID for the structure you wish to accept the contracts at. If left empty the program statistics page will not track if the contract is actually made at the correct structure or not. To get the ID for the structure see readme for getting structure IDs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="blue_loot_npc_price",
            field=models.BooleanField(
                default=False,
                help_text="Valuate blue loot (Sleeper loot) by NPC buy order prices instead of Jita prices",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="red_loot_npc_price",
            field=models.BooleanField(
                default=False,
                help_text="Valuate red loot (Triglavian loot) by NPC buy order prices instead of Jita prices",
            ),
        ),
    ]
