# Generated by Django 3.2.10 on 2021-12-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="start_location_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="owner",
            field=models.ForeignKey(
                help_text="Player that created the location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="buybackprogram.owner",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="structure_id",
            field=models.BigIntegerField(
                default=None,
                help_text="The ID for the structure you wish to accept the contracts at. If left empty the program statistics page will not track if the contract is actually made at the correct structure or not. To get the ID for the structure see readme for getting structure IDs",
                null=True,
            ),
        ),
    ]
