# Generated by Django 3.2.10 on 2022-01-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="ope_npc_price",
            field=models.BooleanField(
                default=False,
                help_text="Valuate Overseer's Personal Effects (OPE) by NPC buy order prices instead of Jita prices",
            ),
        ),
    ]
