# Generated by Django 3.2.10 on 2022-01-02 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import buybackprogram.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buybackprogram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="start_location_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="owner",
            field=models.ForeignKey(
                help_text="Player that created the location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="buybackprogram.owner",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="structure_id",
            field=models.BigIntegerField(
                blank=True,
                default=None,
                help_text="The ID for the structure you wish to accept the contracts at. If left empty the program statistics page will not track if the contract is actually made at the correct structure or not. To get the ID for the structure see readme for getting structure IDs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="blue_loot_npc_price",
            field=models.BooleanField(
                default=False,
                help_text="Valuate blue loot (Sleeper loot) by NPC buy order prices instead of Jita prices",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="discord_channel_notification",
            field=models.BigIntegerField(
                blank=True,
                help_text="Check if you want to feed new contracts to a discord channel. <b>Requires aa-discordbot app to work</b>",
                null=True,
                verbose_name="Discord channel ID for notifications",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="discord_dm_notification",
            field=models.BooleanField(
                default=False,
                help_text="Check if you want to receive a direct message notification each time a new contract is created. <b>Requires aa-discordbot app to work</b>",
                verbose_name="Discord direct messages for new contracts",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="red_loot_npc_price",
            field=models.BooleanField(
                default=False,
                help_text="Valuate red loot (Triglavian loot) by NPC buy order prices instead of Jita prices",
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disable_notifications", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=models.SET(buybackprogram.models.get_sentinel_user),
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
                "default_permissions": (),
            },
        ),
    ]
