# Generated by Django 3.2.8 on 2021-11-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0002_auto_20211113_1013"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="allow_all_items",
            field=models.BooleanField(
                default=True,
                help_text="Are all items accepted at this location. If set to False each item needs to be assigned with an item tax individually, othwerwise the general tax is applied.",
            ),
        ),
    ]
