# Generated by Django 3.2.10 on 2022-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0002_program_ope_npc_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="blue_loot_npc_price",
            field=models.BooleanField(
                default=False,
                help_text="Use NPC price as value for blue loot",
                verbose_name="NPC price for: Sleeper Components",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="ope_npc_price",
            field=models.BooleanField(
                default=False,
                help_text="Use NPC price as value for OPEs",
                verbose_name="NPC price for: Overseer's Personal Effects",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="red_loot_npc_price",
            field=models.BooleanField(
                default=False,
                help_text="Use NPC price as value for red loot",
                verbose_name="NPC price for: Triglavian Survey Database",
            ),
        ),
    ]
