# Generated by Django 3.2.10 on 2022-01-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0003_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="discord_channel_notification",
            field=models.IntegerField(
                blank=True,
                help_text="Check if you want to feed new contracts to a discord channel. <b>Requires aa-discordbot app to work</b>",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="discord_dm_notification",
            field=models.BooleanField(
                default=False,
                help_text="Check if you want to receive a direct message notification each time a new contract is created. <b>Requires aa-discordbot app to work</b>",
            ),
        ),
    ]
