# Generated by Django 3.2.8 on 2021-11-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0004_alter_general_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="buybackprogram.location",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.PositiveBigIntegerField(
                help_text="Eve Online location ID", primary_key=True, serialize=False
            ),
        ),
    ]
