# Generated by Django 3.2.10 on 2022-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0004_auto_20220108_0819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="discord_channel_notification",
            field=models.BigIntegerField(
                blank=True,
                help_text="Check if you want to feed new contracts to a discord channel. <b>Requires aa-discordbot app or discordproxy app to work</b>",
                null=True,
                verbose_name="Discord channel ID for notifications",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="discord_dm_notification",
            field=models.BooleanField(
                default=False,
                help_text="Check if you want to receive a direct message notification each time a new contract is created. <b>Requires aa-discordbot app or discordproxy app to work</b>",
                verbose_name="Discord direct messages for new contracts",
            ),
        ),
    ]
