# Generated by Django 3.2.8 on 2021-11-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0006_alter_location_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="is_corporation",
        ),
        migrations.AddField(
            model_name="program",
            name="is_corporation",
            field=models.BooleanField(
                default=False,
                help_text="If contracts should be created to an corporation instead of the character tick this box.",
            ),
        ),
    ]
