# Generated by Django 3.2.8 on 2021-11-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0007_auto_20211113_1133"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="name",
        ),
    ]
