# Generated by Django 4.0.6 on 2022-09-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0007_program_expiration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app and see own statics."),
                    (
                        "manage_programs",
                        "Can manage own buyback programs and see own program statics.",
                    ),
                    ("see_leaderboard", "Can see leaderboards for available programs."),
                    ("see_all_statics", "Can see all program statics."),
                ),
            },
        ),
    ]
