# Generated by Django 3.2.8 on 2021-11-15 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0008_remove_program_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="allow_all_items",
            field=models.BooleanField(
                default=True,
                help_text="If true all items are accepted in this program with the default tax unless an item tax is spesified.",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="is_corporation",
            field=models.BooleanField(
                default=False,
                help_text="Tick if contracts should be made to corporation instead of player.",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="location",
            field=models.ForeignKey(
                help_text="Solarystem and station name for contracts.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="buybackprogram.location",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="owner",
            field=models.ForeignKey(
                help_text="Player that the contracts will be created for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="buybackprogram.owner",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="tax",
            field=models.IntegerField(
                default=0,
                help_text="Default tax is applied on all items unless an item spesific tax is assigned",
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
