# Generated by Django 4.0.6 on 2023-03-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybackprogram', '0010_alter_tracking_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='no_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
