# Generated by Django 3.2.8 on 2021-11-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0011_auto_20211126_2036"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPrices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy", models.IntegerField()),
                ("sell", models.IntegerField()),
                ("updated", models.DateTimeField()),
            ],
        ),
    ]
