# Generated by Django 3.2.8 on 2021-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0012_itemprices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemprices",
            name="buy",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="itemprices",
            name="sell",
            field=models.BigIntegerField(),
        ),
    ]
