# Generated by Django 3.2.9 on 2021-11-30 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0005_type_materials_and_sections'),
        ('buybackprogram', '0014_auto_20211129_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprices',
            name='item_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evetype'),
            preserve_default=False,
        ),
    ]
