# Generated by Django 3.2.9 on 2021-11-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0017_alter_itemprices_item_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemprices",
            old_name="item_type",
            new_name="eve_type",
        ),
    ]
