# Generated by Django 3.2.9 on 2021-11-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0020_alter_program_allow_all_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program",
            old_name="isk_cubic_tax",
            new_name="price_dencity_tax",
        ),
        migrations.RenameField(
            model_name="program",
            old_name="isk_cubic_treshold",
            new_name="price_dencity_treshold",
        ),
    ]
