# Generated by Django 3.2.9 on 2021-11-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0021_auto_20211130_0707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="hauling_fuel_cost",
            field=models.IntegerField(
                default=0,
                help_text="ISK per m³ that will be removed from the buy price ie. to cover jump freighet fuel costs. <b>Should not be used with price dencity modifier</b>",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="price_dencity_modifier",
            field=models.BooleanField(
                default=False,
                help_text="Should we modify buy prices for items with high volume and low value ie. T1 industrial hulls. <b>Should not be used with hauling fuel cost</b>",
            ),
        ),
    ]
