# Generated by Django 3.2.10 on 2021-12-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybackprogram', '0023_contract_contractitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_expired',
            field=models.DateTimeField(null=True),
        ),
    ]
