# Generated by Django 3.2.8 on 2021-12-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0024_auto_20211209_1001"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="allow_unpacked_items",
            field=models.BooleanField(
                default=False,
                help_text="Do you want to allow unpacked items in this program such as assembled ship hulls?",
            ),
        ),
    ]
