# Generated by Django 3.2.8 on 2021-12-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0026_tracking_trackingitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracking",
            name="tracking_number",
        ),
    ]
