# Generated by Django 3.2.8 on 2021-12-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0027_remove_tracking_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking",
            name="tracking_number",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
