# Generated by Django 3.2.8 on 2021-12-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_merge_20211026_0919"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("buybackprogram", "0030_auto_20211213_1841"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="restricted_to_group",
            field=models.ManyToManyField(
                blank=True,
                help_text="The group(s) that will be able to see this buyback program. If none is selected program is open for all.",
                related_name="buybackprogram_require_groups",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="restricted_to_state",
            field=models.ManyToManyField(
                blank=True,
                help_text="The state(s) that will be able to see this buyback program. If none is selected program is open for all.",
                related_name="buybackprogram_require_states",
                to="authentication.State",
            ),
        ),
    ]
