# Generated by Django 3.2.8 on 2021-12-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0031_auto_20211213_1842"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app."),
                    ("manage_programs", "Can manage buyback programs"),
                ),
            },
        ),
    ]
