# Generated by Django 3.2.8 on 2021-12-16 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buybackprogram", "0032_alter_general_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app."),
                    ("manage_programs", "Can manage own buyback programs"),
                    ("manage_all_programs", "Can manage all buyback programs"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="tracking",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="buybackprogram.program",
            ),
        ),
    ]
